features:
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
  logo: true
  name: true
  node_user_picture: 1
  slogan: true
facebook_url: 'https://www.facebook.com/zymphonies'
twitter_url: 'https://twitter.com/zymphonies'
google_plus_url: 'https://plus.google.com/+ZymphoniesTechnologies'
linkedin_url: 'http://www.linkedin.com/company/zymphonies'
pinterest_url: 'https://www.pinterest.com/zymphonies'
rss_url: rss.xml
copyright_text: 'Copyright 2017Â· All rights reserved'
show_social_icon: 1
show_credit_link: 0
_core:
  default_config_hash: FIKpUAUBhRvu30trYoPz9z7O8dAeWlZ3GILxKamftng
langcode: it
logo:
  use_default: 0
  path: 'public://logo-pronto-arcoes.png'
favicon:
  use_default: 1
